### ISSUE TITLE
Document the expected Sigstore CLI interface

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/sigstore-conformance#11]
In order to test the entire matrix, we need a uniform interface that all Sigstore implementations can expose.

The highest common denominator is currently Docker, so whatever interface we produce will need to work with the primitives/mechanisms that Docker exposes (namely environments, volumes, and entrypoints).

In terms of a baseline, we'll need:

* A "sign" interface, which takes an input (e.g. file or env var) and produces the signature (base64 encoded) and certificate (X.509 PEM encoded) corresponding to it
* A "verify" interface, which takes the input, signature, and certificate and returns a true/false value for the signature and certificate's validitity

Additionally, we'll want to parameterize those interfaces a bit, to exercise other functionality:

* For implementations that support it, we'll probably want a "staging" flag that uses Sigstore's staging instances for signing/verification rather than the production instances
* We'll probably want a way to override the OIDC token, to test signing/verification with non-GitHub identities

**Comment by tetsuo-cpp** [comment]
This will be partially achieved in #5, but once it's merged we should take some time to think it through and refine it.

**Comment by tetsuo-cpp** [comment]
This interface will not exist concretely in code as each implementation will be responsible for writing a wrapper for it. However, we should spend some documenting what the expectations are for the entrypoint.
